[
  {
    "id": 1,
    "commonName": "Rosa",
    "scientificName": "Rosa",
    "img": "https://mamabruja.com/wp-content/uploads/2021/10/ivan-jevtic-p7mo8-CG5Gs-unsplash-2-1200x800.jpg",
    "type": "Arbusto",
    "origin": "Asia",
    "floweringSeason": "Primavera",
    "sunExposure": "Sol pleno",
    "watering": "Moderado"
  },
  {
    "id": 2,
    "commonName": "Girasol",
    "scientificName": "Helianthus annuus",
    "img": "https://zinniaflors.com/modules/ph_simpleblog/covers/104.jpg",
    "type": "Anual",
    "origin": "América del Norte",
    "floweringSeason": "Verano",
    "sunExposure": "Sol pleno",
    "watering": "Moderado"
  },
  {
    "id": 3,
    "commonName": "Tulipán",
    "scientificName": "Tulipa",
    "img": "https://www.floristeriamorris.com/wp-content/uploads/todo-lo-que-necesitas-saber-sobre-tulipanes-cuidados-floracion-y-colores.jpg",
    "type": "Bulbosa",
    "origin": "Asia Central",
    "floweringSeason": "Primavera",
    "sunExposure": "Sol pleno",
    "watering": "Moderado"
  },
  {
    "id": 4,
    "commonName": "Narciso",
    "scientificName": "Narcissus",
    "img": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiUpMltGyNDbyx_62cTiXQRlW1LOLFTtALRaC-IiZk2FzvTchZ5ZMpXODNqlodZd75_M6bwT4r6kBX44Vq_UqWoKkzIT3pbdNb6n522x-kff8rJCwceZF2uziMlx5BNTmN_yH_x8srSezw/s1600/narciso-blanco-y-rosa.jpg",
    "type": "Bulbosa",
    "origin": "Europa",
    "floweringSeason": "Primavera",
    "sunExposure": "Sol pleno",
    "watering": "Moderado"
  },
  {
    "id": 5,
    "commonName": "Lirio",
    "scientificName": "Lilium",
    "img": "https://www.interflora.es/blog/wp-content/uploads/lirios-grandes-1-1024x894.jpg",
    "type": "Perenne",
    "origin": "Hemisferio Norte",
    "floweringSeason": "Verano",
    "sunExposure": "Sol pleno",
    "watering": "Moderado"
  },
  {
    "id": 6,
    "commonName": "Caléndula",
    "scientificName": "Calendula officinalis",
    "img": "https://sembramos.com.co/wp-content/uploads/2022/12/calendula-planta-pixabay-1200x800.jpg",
    "type": "Anual",
    "origin": "Europa del Sur",
    "floweringSeason": "Primavera a Otoño",
    "sunExposure": "Sol pleno",
    "watering": "Moderado"
  },
  {
    "id": 7,
    "commonName": "Clavel",
    "scientificName": "Dianthus caryophyllus",
    "img": "https://inaturalist-open-data.s3.amazonaws.com/photos/38101/large.jpg",
    "type": "Perenne",
    "origin": "Región Mediterránea",
    "floweringSeason": "Primavera a Verano",
    "sunExposure": "Sol pleno",
    "watering": "Moderado"
  },
  {
    "id": 8,
    "commonName": "Pensamiento",
    "scientificName": "Viola tricolor",
    "img": "https://estag.fimagenes.com/img/v2/7e5/1103989_534017_900.jpg",
    "type": "Anual",
    "origin": "Europa",
    "floweringSeason": "Primavera a Verano",
    "sunExposure": "Sol pleno",
    "watering": "Moderado"
  },
  {
    "id": 9,
    "commonName": "Hortensia",
    "scientificName": "Hydrangea macrophylla",
    "img": "https://www.consumer.es/app/uploads/2019/07/img_hortensia-azul.jpg",
    "type": "Arbusto",
    "origin": "Asia",
    "floweringSeason": "Verano",
    "sunExposure": "Sombra parcial",
    "watering": "Abundante"
  },
  {
    "id": 10,
    "commonName": "Azalea",
    "scientificName": "Rhododendron",
    "img": "https://bouqs.com/blog/wp-content/uploads/2024/08/shutterstock_2470487527-min.jpg",
    "type": "Arbusto",
    "origin": "Asia",
    "floweringSeason": "Primavera",
    "sunExposure": "Sombra parcial",
    "watering": "Moderado"
  },
  {
    "id": 11,
    "commonName": "Peonía",
    "scientificName": "Paeonia",
    "img": "https://alblancatelier.com/cdn/shop/products/simbologiapeoniaalblanc2_800x.jpg?v=1745654627",
    "type": "Perenne",
    "origin": "Asia",
    "floweringSeason": "Primavera a Verano",
    "sunExposure": "Sol pleno",
    "watering": "Moderado"
  },
  {
    "id": 12,
    "commonName": "Orquídea",
    "scientificName": "Orchidaceae",
    "img": "https://www.floresyplantas.net/wp-content/uploads/flor-de-phalaenopsis.jpg",
    "type": "Epífita",
    "origin": "Mundial",
    "floweringSeason": "Variable",
    "sunExposure": "Luz indirecta",
    "watering": "Moderado"
  },
  {
    "id": 13,
    "commonName": "Iris",
    "scientificName": "Iris germanica",
    "img": "https://www.lasaponaria.es/img/cms/800px-purple_iris_flower.jpg",
    "type": "Perenne",
    "origin": "Europa",
    "floweringSeason": "Primavera",
    "sunExposure": "Sol pleno",
    "watering": "Moderado"
  },
  {
    "id": 14,
    "commonName": "Geranio",
    "scientificName": "Pelargonium",
    "img": "https://jardineros.com.co/wp-content/uploads/2022/01/Geranio-o-novio2.jpg",
    "type": "Perenne",
    "origin": "África del Sur",
    "floweringSeason": "Primavera a Verano",
    "sunExposure": "Sol pleno",
    "watering": "Moderado"
  },
  {
    "id": 15,
    "commonName": "Lavanda",
    "scientificName": "Lavandula angustifolia",
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Single_lavender_flower02.jpg/1200px-Single_lavender_flower02.jpg",
    "type": "Arbusto",
    "origin": "Región Mediterránea",
    "floweringSeason": "Verano",
    "sunExposure": "Sol pleno",
    "watering": "Bajo"
  },
  {
    "id": 16,
    "commonName": "Salvia",
    "scientificName": "Salvia officinalis",
    "img": "https://img77.uenicdn.com/image/upload/v1688101535/business/a377478f-3db9-4a6a-b011-d051a0c24541.jpg",
    "type": "Arbusto",
    "origin": "Región Mediterránea",
    "floweringSeason": "Verano",
    "sunExposure": "Sol pleno",
    "watering": "Moderado"
  },
  {
    "id": 17,
    "commonName": "Tomillo",
    "scientificName": "Thymus vulgaris",
    "img": "https://upload.wikimedia.org/wikipedia/commons/d/d0/Starr-080812-9700-Thymus_vulgaris-leaves-Makawao-Maui_%2824807095872%29.jpg",
    "type": "Arbusto",
    "origin": "Región Mediterránea",
    "floweringSeason": "Verano",
    "sunExposure": "Sol pleno",
    "watering": "Bajo"
  },
  {
    "id": 18,
    "commonName": "Menta",
    "scientificName": "Mentha",
    "img": "https://www.lasaponaria.es/img/cms/menta-immagine.jpg",
    "type": "Perenne",
    "origin": "Europa y Asia",
    "floweringSeason": "Verano",
    "sunExposure": "Sol pleno a sombra parcial",
    "watering": "Abundante"
  },
  {
    "id": 19,
    "commonName": "Albahaca",
    "scientificName": "Ocimum basilicum",
    "img": "https://agroactivocol.com/wp-content/uploads/2020/08/7e2db098-albahaca-basil-adobestock_81129315-scaled-1.jpg.webp",
    "type": "Anual",
    "origin": "India",
    "floweringSeason": "Verano",
    "sunExposure": "Sol pleno",
    "watering": "Moderado"
  },
  {
    "id": 20,
    "commonName": "Perejil",
    "scientificName": "Petroselinum crispum",
    "img": "https://www.finedininglovers.com/es/sites/g/files/xknfdk1706/files/2023-04/ES%20SEO%20Perejil_%C2%A9unsplash_chandan%20chaurasia%20%281%29_0.jpg",
    "type": "Bienal",
    "origin": "Región Mediterránea",
    "floweringSeason": "Verano",
    "sunExposure": "Sol pleno a sombra parcial",
    "watering": "Moderado"
  }
]